### PR TITLE
add pulsegroup example

### PR DESCRIPTION
**Pull request by jepler**
Example to accompany new functionality in 
 * https://github.com/adafruit/circuitpython/pull/6300

wait for that code to be merged before merging this example!

### CODE REVIEW

**Comment by jepler** [comment]
This example is for the Pimoroni Servo 2040 board. It sends commands to all 18 connected servos, making them move in a sinusoidal fashion. The number printed on the REPL is the milliseconds between updates, ideally 20.

**Comment by jepler** [comment]
Limor requests that the example be changed so that the servos start on 2.5ms boundaries, so: 0ms, 2.5ms, ..., 17.5ms, 0ms, ...

**Comment by jepler** [comment]
Updated per Limor's request

**Review by dhalbert — APPROVED** [review]
Thanks! Tested with two servos on a Pi Pico.

**Pull request merged**
