### PR TITLE
Add `Program` class, type information

### PR DESCRIPTION
**Pull request by jepler**
An instance of the `Program` class has the `assembled` property as well as the `pio_kwargs` property. This allows passing information from the assembler to the `StateMachine` constructor, in a way that can be extended in future versions (e.g., for .wrap / .wrap_target)

This re-indents a lot of code so it may be better viewed with whitespace changes hidden.

Tests are added for the limits of the side-set and delay values. An off-by-one bug with the sideset_value limit was fixed.

Closes: #28

### CODE REVIEW

**Comment by jepler** [comment]
@tannewt should the `assembled` property be in the `kwargs` instead?

**Comment by tannewt** [comment]
I don't think so. It's called `program` and is a positional argument in `StateMachine`.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add an example that uses the Program class. That way we can show folks how to use it.

Otherwise, this looks like a good change! It'll be nice to get kwargs out of it.

**Comment by jepler** [comment]
Merged with the latest & converted the txuart example to use Program and **pio_kwargs (not actually tested on HW)

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
